server:
  port: 8090

spring:
  application:
    name: supply-system-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ruijie.supplysystem: info
