spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_supply_task?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: supply_user
    password: supply123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000

logging:
  level:
    root: info
    com.ruijie.supplytask: debug
