spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/db_supply_task?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false}
    username: ${DB_USERNAME:supply_user}
    password: ${DB_PASSWORD:change_me}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000

logging:
  level:
    root: info
    com.ruijie.supplytask: info
